name: habits_flutter
description: A new Flutter project with Serverpod.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  app_client:
    path: ../packages/app_client
  app_shared:
    path: ../packages/app_shared
  bloc: ^8.1.4
  dartz: ^0.10.1
  equatable: ^2.0.5
  firebase_auth: ^4.18.0
  firebase_core: ^2.27.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.4.1
  get_it: ^7.6.7
  go_router: ^13.2.2
  habits_client:
    path: ../habits_client
  habits_shared:
    path: ../habits_shared
  intl: ^0.19.0
  logging: ^1.2.0
  platform: ^3.1.4
  provider: ^6.1.2
  serverpod_auth_client: 1.2.6
  serverpod_auth_email_flutter: 1.2.6
  serverpod_auth_shared_flutter: 1.2.6
  serverpod_flutter: 1.2.6
  timezone: ^0.9.2

dev_dependencies:
  bloc_test: ^9.1.6
  build_runner: ^2.4.9
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
