name: habits_shared
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.0-282.2.beta

# Add regular dependencies here.
dependencies:
  app_shared:
    path: ../packages/app_shared
  freezed_annotation: ^2.4.1
  habits_client:
    path: ../habits_client
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ^2.4.9
  freezed: ^2.5.2
  json_serializable: ^6.7.1
  lints: ^3.0.0
  test: ^1.24.0
  very_good_analysis: ^5.1.0
