include: package:very_good_analysis/analysis_options.5.1.0.yaml
linter:
  rules:
    public_member_api_docs: true
    omit_local_variable_types: false

analyzer:
  errors:
    todo: ignore
    flutter_style_todos: ignore
  exclude:
      - "**.freezed.dart"
      - "**.g.dart"
