name: app_client
description: App-agnostic infrastructure to build apps with Flutter and Serverpod.
version: 0.1.0+1
publish_to: none

environment:
  sdk: "^3.3.0"

dependencies:
  app_shared:
    path: ../app_shared
  crypt: ^4.3.1
  dartz: ^0.10.1
  email_validator: ^2.1.17
  equatable: ^2.0.5
  firebase_auth: ^4.15.0
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1
  get_it: ^7.6.4
  google_sign_in: ^6.1.6
  habits_client:
    path: ../../habits_client
  http: ^1.2.0
  json_annotation: ^4.8.1
  logging: ^1.2.0
  matcher: ^0.12.16
  meta: ^1.14.0
  platform: ^3.1.3
  serverpod_auth_client: 2.0.0
  serverpod_auth_shared_flutter: 2.0.0
  serverpod_client: 2.0.0
  sign_in_with_apple: ^5.0.0
  uuid: ^4.2.1

dev_dependencies:
  build_runner: ^2.4.7
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0
