name: data_serverpod
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.4.0-282.2.beta

# Add regular dependencies here.
dependencies:
  data:
    path: ../data

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
