// Mocks generated by Mockito 5.4.4 from annotations
// in habits_server/test/mocks/user_model_mock.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:habits_shared/src/models/user.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:serverpod/serverpod.dart' as _i2;
import 'package:serverpod_auth_server/src/generated/auth_key.dart' as _i3;
import 'package:serverpod_auth_server/src/generated/user_info.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeTable_0 extends _i1.SmartFake implements _i2.Table {
  _FakeTable_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAuthKey_1 extends _i1.SmartFake implements _i3.AuthKey {
  _FakeAuthKey_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDateTime_2 extends _i1.SmartFake implements DateTime {
  _FakeDateTime_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserInfo_3 extends _i1.SmartFake implements _i4.UserInfo {
  _FakeUserInfo_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$UserCopyWith_4<$Res> extends _i1.SmartFake
    implements _i5.$UserCopyWith<$Res> {
  _Fake$UserCopyWith_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthKey].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthKey extends _i1.Mock implements _i3.AuthKey {
  @override
  int get userId => (super.noSuchMethod(
        Invocation.getter(#userId),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  set userId(int? _userId) => super.noSuchMethod(
        Invocation.setter(
          #userId,
          _userId,
        ),
        returnValueForMissingStub: null,
      );

  @override
  String get hash => (super.noSuchMethod(
        Invocation.getter(#hash),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#hash),
        ),
        returnValueForMissingStub: _i6.dummyValue<String>(
          this,
          Invocation.getter(#hash),
        ),
      ) as String);

  @override
  set hash(String? _hash) => super.noSuchMethod(
        Invocation.setter(
          #hash,
          _hash,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set key(String? _key) => super.noSuchMethod(
        Invocation.setter(
          #key,
          _key,
        ),
        returnValueForMissingStub: null,
      );

  @override
  List<String> get scopeNames => (super.noSuchMethod(
        Invocation.getter(#scopeNames),
        returnValue: <String>[],
        returnValueForMissingStub: <String>[],
      ) as List<String>);

  @override
  set scopeNames(List<String>? _scopeNames) => super.noSuchMethod(
        Invocation.setter(
          #scopeNames,
          _scopeNames,
        ),
        returnValueForMissingStub: null,
      );

  @override
  String get method => (super.noSuchMethod(
        Invocation.getter(#method),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#method),
        ),
        returnValueForMissingStub: _i6.dummyValue<String>(
          this,
          Invocation.getter(#method),
        ),
      ) as String);

  @override
  set method(String? _method) => super.noSuchMethod(
        Invocation.setter(
          #method,
          _method,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.Table get table => (super.noSuchMethod(
        Invocation.getter(#table),
        returnValue: _FakeTable_0(
          this,
          Invocation.getter(#table),
        ),
        returnValueForMissingStub: _FakeTable_0(
          this,
          Invocation.getter(#table),
        ),
      ) as _i2.Table);

  @override
  set id(int? _id) => super.noSuchMethod(
        Invocation.setter(
          #id,
          _id,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.AuthKey copyWith({
    int? id,
    int? userId,
    String? hash,
    String? key,
    List<String>? scopeNames,
    String? method,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #copyWith,
          [],
          {
            #id: id,
            #userId: userId,
            #hash: hash,
            #key: key,
            #scopeNames: scopeNames,
            #method: method,
          },
        ),
        returnValue: _FakeAuthKey_1(
          this,
          Invocation.method(
            #copyWith,
            [],
            {
              #id: id,
              #userId: userId,
              #hash: hash,
              #key: key,
              #scopeNames: scopeNames,
              #method: method,
            },
          ),
        ),
        returnValueForMissingStub: _FakeAuthKey_1(
          this,
          Invocation.method(
            #copyWith,
            [],
            {
              #id: id,
              #userId: userId,
              #hash: hash,
              #key: key,
              #scopeNames: scopeNames,
              #method: method,
            },
          ),
        ),
      ) as _i3.AuthKey);

  @override
  Map<String, dynamic> toJson() => (super.noSuchMethod(
        Invocation.method(
          #toJson,
          [],
        ),
        returnValue: <String, dynamic>{},
        returnValueForMissingStub: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  Map<String, dynamic> toJsonForProtocol() => (super.noSuchMethod(
        Invocation.method(
          #toJsonForProtocol,
          [],
        ),
        returnValue: <String, dynamic>{},
        returnValueForMissingStub: <String, dynamic>{},
      ) as Map<String, dynamic>);
}

/// A class which mocks [UserInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserInfo extends _i1.Mock implements _i4.UserInfo {
  @override
  String get userIdentifier => (super.noSuchMethod(
        Invocation.getter(#userIdentifier),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#userIdentifier),
        ),
        returnValueForMissingStub: _i6.dummyValue<String>(
          this,
          Invocation.getter(#userIdentifier),
        ),
      ) as String);

  @override
  set userIdentifier(String? _userIdentifier) => super.noSuchMethod(
        Invocation.setter(
          #userIdentifier,
          _userIdentifier,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set userName(String? _userName) => super.noSuchMethod(
        Invocation.setter(
          #userName,
          _userName,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set fullName(String? _fullName) => super.noSuchMethod(
        Invocation.setter(
          #fullName,
          _fullName,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set email(String? _email) => super.noSuchMethod(
        Invocation.setter(
          #email,
          _email,
        ),
        returnValueForMissingStub: null,
      );

  @override
  DateTime get created => (super.noSuchMethod(
        Invocation.getter(#created),
        returnValue: _FakeDateTime_2(
          this,
          Invocation.getter(#created),
        ),
        returnValueForMissingStub: _FakeDateTime_2(
          this,
          Invocation.getter(#created),
        ),
      ) as DateTime);

  @override
  set created(DateTime? _created) => super.noSuchMethod(
        Invocation.setter(
          #created,
          _created,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set imageUrl(String? _imageUrl) => super.noSuchMethod(
        Invocation.setter(
          #imageUrl,
          _imageUrl,
        ),
        returnValueForMissingStub: null,
      );

  @override
  List<String> get scopeNames => (super.noSuchMethod(
        Invocation.getter(#scopeNames),
        returnValue: <String>[],
        returnValueForMissingStub: <String>[],
      ) as List<String>);

  @override
  set scopeNames(List<String>? _scopeNames) => super.noSuchMethod(
        Invocation.setter(
          #scopeNames,
          _scopeNames,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get blocked => (super.noSuchMethod(
        Invocation.getter(#blocked),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  set blocked(bool? _blocked) => super.noSuchMethod(
        Invocation.setter(
          #blocked,
          _blocked,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.Table get table => (super.noSuchMethod(
        Invocation.getter(#table),
        returnValue: _FakeTable_0(
          this,
          Invocation.getter(#table),
        ),
        returnValueForMissingStub: _FakeTable_0(
          this,
          Invocation.getter(#table),
        ),
      ) as _i2.Table);

  @override
  set id(int? _id) => super.noSuchMethod(
        Invocation.setter(
          #id,
          _id,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.UserInfo copyWith({
    int? id,
    String? userIdentifier,
    String? userName,
    String? fullName,
    String? email,
    DateTime? created,
    String? imageUrl,
    List<String>? scopeNames,
    bool? blocked,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #copyWith,
          [],
          {
            #id: id,
            #userIdentifier: userIdentifier,
            #userName: userName,
            #fullName: fullName,
            #email: email,
            #created: created,
            #imageUrl: imageUrl,
            #scopeNames: scopeNames,
            #blocked: blocked,
          },
        ),
        returnValue: _FakeUserInfo_3(
          this,
          Invocation.method(
            #copyWith,
            [],
            {
              #id: id,
              #userIdentifier: userIdentifier,
              #userName: userName,
              #fullName: fullName,
              #email: email,
              #created: created,
              #imageUrl: imageUrl,
              #scopeNames: scopeNames,
              #blocked: blocked,
            },
          ),
        ),
        returnValueForMissingStub: _FakeUserInfo_3(
          this,
          Invocation.method(
            #copyWith,
            [],
            {
              #id: id,
              #userIdentifier: userIdentifier,
              #userName: userName,
              #fullName: fullName,
              #email: email,
              #created: created,
              #imageUrl: imageUrl,
              #scopeNames: scopeNames,
              #blocked: blocked,
            },
          ),
        ),
      ) as _i4.UserInfo);

  @override
  Map<String, dynamic> toJson() => (super.noSuchMethod(
        Invocation.method(
          #toJson,
          [],
        ),
        returnValue: <String, dynamic>{},
        returnValueForMissingStub: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  Map<String, dynamic> toJsonForProtocol() => (super.noSuchMethod(
        Invocation.method(
          #toJsonForProtocol,
          [],
        ),
        returnValue: <String, dynamic>{},
        returnValueForMissingStub: <String, dynamic>{},
      ) as Map<String, dynamic>);
}

/// A class which mocks [User].
///
/// See the documentation for Mockito's code generation for more information.
class MockUser extends _i1.Mock implements _i5.User {
  @override
  String get uid => (super.noSuchMethod(
        Invocation.getter(#uid),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#uid),
        ),
        returnValueForMissingStub: _i6.dummyValue<String>(
          this,
          Invocation.getter(#uid),
        ),
      ) as String);

  @override
  _i5.$UserCopyWith<_i5.User> get copyWith => (super.noSuchMethod(
        Invocation.getter(#copyWith),
        returnValue: _Fake$UserCopyWith_4<_i5.User>(
          this,
          Invocation.getter(#copyWith),
        ),
        returnValueForMissingStub: _Fake$UserCopyWith_4<_i5.User>(
          this,
          Invocation.getter(#copyWith),
        ),
      ) as _i5.$UserCopyWith<_i5.User>);

  @override
  Map<String, dynamic> toJson() => (super.noSuchMethod(
        Invocation.method(
          #toJson,
          [],
        ),
        returnValue: <String, dynamic>{},
        returnValueForMissingStub: <String, dynamic>{},
      ) as Map<String, dynamic>);
}
