name: app_shared
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: "^3.3.0"

dependencies:
  dartz: ^0.10.1
  email_validator: ^2.1.17
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  logging: ^1.2.0
  meta: ^1.14.0
  serverpod_auth_client: 2.0.0
  timezone: ^0.9.2

dev_dependencies:
  build_runner: ^2.4.9
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  mocktail: ^1.0.3
  test: ^1.25.2
  very_good_analysis: ^5.1.0
